module top_model
  #(
    parameter int parallel_mems = 2,    //GOTO: /memory_model
    parameter int mem_sections = 8,     //GOTO: /memory_model
    parameter int fault_count = 64,     //GOTO: /faults_database
    parameter int disturb_count = 4,    //GOTO: /faults_database/fault_model
    parameter int couple_count = 16,    //GOTO: /faults_database/fault_model
    parameter int watch_depth = 8,      //GOTO: /faults_database/fault_model
    parameter int addrW = 13,
    parameter int dataW = 64
  ) (
    input  logic clk,
    input  logic nres,
    //MEM1 Memory Port
    input  logic             mem1_cs_n,
    input  logic [addrW-1:0] mem1_addr,
    input  logic             mem1_we_n,
    input  logic [dataW-1:0] mem1_bwe_n,
    input  logic [dataW-1:0] mem1_din,
    input  logic             mem1_re_n,
    output logic [dataW-1:0] mem1_dout,
    //MEM2 Memory Port
    input  logic             mem2_cs_n,
    input  logic [addrW-1:0] mem2_addr,
    input  logic             mem2_we_n,
    input  logic [dataW-1:0] mem2_bwe_n,
    input  logic [dataW-1:0] mem2_din,
    input  logic             mem2_re_n,
    output logic [dataW-1:0] mem2_dout,

    `ifndef SYNTHESIS
    // ================================ SIMULATION TOP MODEL ================================

    //Simulation Logging
    input  integer log_fd,
    //MEM1 MBIST Interface
    input  logic                                    [4:0] mem1_mbist_mode,
    input  logic                       [mem_sections-1:0] mem1_mbist_en,
    output logic       [(mem_sections*parallel_mems)-1:0] mem1_mbist_fault,
    output logic     [(mem_sections*parallel_mems*8)-1:0] mem1_mbist_fault_state,
    output logic [(mem_sections*parallel_mems*addrW)-1:0] mem1_mbist_fault_addr,
    output logic               [(mem_sections*dataW)-1:0] mem1_mbist_fault_data,
    output logic               [(mem_sections*dataW)-1:0] mem1_mbist_fault_dout,
    output logic                       [mem_sections-1:0] mem1_mbist_done,
    //MEM2 MBIST Interface
    input  logic                                    [4:0] mem2_mbist_mode,
    input  logic                       [mem_sections-1:0] mem2_mbist_en,
    output logic       [(mem_sections*parallel_mems)-1:0] mem2_mbist_fault,
    output logic     [(mem_sections*parallel_mems*8)-1:0] mem2_mbist_fault_state,
    output logic [(mem_sections*parallel_mems*addrW)-1:0] mem2_mbist_fault_addr,
    output logic               [(mem_sections*dataW)-1:0] mem2_mbist_fault_data,
    output logic               [(mem_sections*dataW)-1:0] mem2_mbist_fault_dout,
    output logic                       [mem_sections-1:0] mem2_mbist_done
  );

    //MEM1 Instance
    memory_model #(
      .base_index(parallel_mems*mem_sections*0),
      .mem_len(fault_count),
      .parallel_mems(parallel_mems),
      .mem_sections(mem_sections),
      .fault_count(fault_count/2),
      .disturb_count(disturb_count),
      .couple_count(couple_count),
      .watch_depth(watch_depth),
      .addrW(addrW),
      .dataW(dataW)
    ) MEM1 (
      `ifndef SYNTHESIS
      .log_fd(log_fd),
      `endif
      .clk(clk),
      .nres(nres),
      //Memory Port
      .cs_n(mem1_cs_n),
      .addr(mem1_addr),
      // Write
      .we_n(mem1_we_n),
      .bwe_n(mem1_bwe_n),
      .din(mem1_din),
      // Read
      .re_n(mem1_re_n),
      .dout(mem1_dout),
      //MBIST Interface
      .mbist_mode(mem1_mbist_mode),
      .mbist_en(mem1_mbist_en),
      .mbist_fault(mem1_mbist_fault),
      .mbist_fault_state(mem1_mbist_fault_state),
      .mbist_fault_addr(mem1_mbist_fault_addr),
      .mbist_fault_data(mem1_mbist_fault_data),
      .mbist_fault_dout(mem1_mbist_fault_dout),
      .mbist_done(mem1_mbist_done)
    );

    //MEM2 Instance
    memory_model #(
      .base_index(parallel_mems*mem_sections*1),
      .mem_len(fault_count),
      .parallel_mems(parallel_mems),
      .mem_sections(mem_sections),
      .fault_count(fault_count/2),
      .disturb_count(disturb_count),
      .couple_count(couple_count),
      .watch_depth(watch_depth),
      .addrW(addrW),
      .dataW(dataW)
    ) MEM2 (
      `ifndef SYNTHESIS
      .log_fd(log_fd),
      `endif
      .clk(clk),
      .nres(nres),
      //Memory Port
      .cs_n(mem2_cs_n),
      .addr(mem2_addr),
      // Write
      .we_n(mem2_we_n),
      .bwe_n(mem2_bwe_n),
      .din(mem2_din),
      // Read
      .re_n(mem2_re_n),
      .dout(mem2_dout),
      //MBIST Interface
      .mbist_mode(mem2_mbist_mode),
      .mbist_en(mem2_mbist_en),
      .mbist_fault(mem2_mbist_fault),
      .mbist_fault_state(mem2_mbist_fault_state),
      .mbist_fault_addr(mem2_mbist_fault_addr),
      .mbist_fault_data(mem2_mbist_fault_data),
      .mbist_fault_dout(mem2_mbist_fault_dout),
      .mbist_done(mem2_mbist_done)
    );

    `else
    // ================================ SYNTHESIS TOP MODEL ================================

    //Synthesis Power Pins
    inout  VPWR,
    inout  VGND,
    //MEM1 MBIST Interface
    input  logic       [4:0] mem1_mbist_mode,
    input  logic             mem1_mbist_en_C01_C02,
    input  logic             mem1_mbist_en_C03_C04,
    input  logic             mem1_mbist_en_C05_C06,
    input  logic             mem1_mbist_en_C07_C08,
    input  logic             mem1_mbist_en_C09_C10,
    input  logic             mem1_mbist_en_C11_C12,
    input  logic             mem1_mbist_en_C13_C14,
    input  logic             mem1_mbist_en_C15_C16,
    output logic             mem1_mbist_fault_C01,
    output logic             mem1_mbist_fault_C02,
    output logic             mem1_mbist_fault_C03,
    output logic             mem1_mbist_fault_C04,
    output logic             mem1_mbist_fault_C05,
    output logic             mem1_mbist_fault_C06,
    output logic             mem1_mbist_fault_C07,
    output logic             mem1_mbist_fault_C08,
    output logic             mem1_mbist_fault_C09,
    output logic             mem1_mbist_fault_C10,
    output logic             mem1_mbist_fault_C11,
    output logic             mem1_mbist_fault_C12,
    output logic             mem1_mbist_fault_C13,
    output logic             mem1_mbist_fault_C14,
    output logic             mem1_mbist_fault_C15,
    output logic             mem1_mbist_fault_C16,
    output logic       [7:0] mem1_mbist_fault_state_C01,
    output logic       [7:0] mem1_mbist_fault_state_C02,
    output logic       [7:0] mem1_mbist_fault_state_C03,
    output logic       [7:0] mem1_mbist_fault_state_C04,
    output logic       [7:0] mem1_mbist_fault_state_C05,
    output logic       [7:0] mem1_mbist_fault_state_C06,
    output logic       [7:0] mem1_mbist_fault_state_C07,
    output logic       [7:0] mem1_mbist_fault_state_C08,
    output logic       [7:0] mem1_mbist_fault_state_C09,
    output logic       [7:0] mem1_mbist_fault_state_C10,
    output logic       [7:0] mem1_mbist_fault_state_C11,
    output logic       [7:0] mem1_mbist_fault_state_C12,
    output logic       [7:0] mem1_mbist_fault_state_C13,
    output logic       [7:0] mem1_mbist_fault_state_C14,
    output logic       [7:0] mem1_mbist_fault_state_C15,
    output logic       [7:0] mem1_mbist_fault_state_C16,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C01,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C02,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C03,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C04,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C05,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C06,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C07,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C08,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C09,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C10,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C11,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C12,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C13,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C14,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C15,
    output logic [addrW-1:0] mem1_mbist_fault_addr_C16,
    output logic [dataW-1:0] mem1_mbist_fault_data_C01,
    output logic [dataW-1:0] mem1_mbist_fault_data_C02,
    output logic [dataW-1:0] mem1_mbist_fault_data_C03,
    output logic [dataW-1:0] mem1_mbist_fault_data_C04,
    output logic [dataW-1:0] mem1_mbist_fault_data_C05,
    output logic [dataW-1:0] mem1_mbist_fault_data_C06,
    output logic [dataW-1:0] mem1_mbist_fault_data_C07,
    output logic [dataW-1:0] mem1_mbist_fault_data_C08,
    output logic [dataW-1:0] mem1_mbist_fault_data_C09,
    output logic [dataW-1:0] mem1_mbist_fault_data_C10,
    output logic [dataW-1:0] mem1_mbist_fault_data_C11,
    output logic [dataW-1:0] mem1_mbist_fault_data_C12,
    output logic [dataW-1:0] mem1_mbist_fault_data_C13,
    output logic [dataW-1:0] mem1_mbist_fault_data_C14,
    output logic [dataW-1:0] mem1_mbist_fault_data_C15,
    output logic [dataW-1:0] mem1_mbist_fault_data_C16,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C01,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C02,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C03,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C04,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C05,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C06,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C07,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C08,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C09,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C10,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C11,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C12,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C13,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C14,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C15,
    output logic [dataW-1:0] mem1_mbist_fault_dout_C16,
    output logic             mem1_mbist_done_C01_C02,
    output logic             mem1_mbist_done_C03_C04,
    output logic             mem1_mbist_done_C05_C06,
    output logic             mem1_mbist_done_C07_C08,
    output logic             mem1_mbist_done_C09_C10,
    output logic             mem1_mbist_done_C11_C12,
    output logic             mem1_mbist_done_C13_C14,
    output logic             mem1_mbist_done_C15_C16,
    //MEM2 MBIST Interface
    input  logic       [4:0] mem2_mbist_mode,
    input  logic             mem2_mbist_en_C01_C02,
    input  logic             mem2_mbist_en_C03_C04,
    input  logic             mem2_mbist_en_C05_C06,
    input  logic             mem2_mbist_en_C07_C08,
    input  logic             mem2_mbist_en_C09_C10,
    input  logic             mem2_mbist_en_C11_C12,
    input  logic             mem2_mbist_en_C13_C14,
    input  logic             mem2_mbist_en_C15_C16,
    output logic             mem2_mbist_fault_C01,
    output logic             mem2_mbist_fault_C02,
    output logic             mem2_mbist_fault_C03,
    output logic             mem2_mbist_fault_C04,
    output logic             mem2_mbist_fault_C05,
    output logic             mem2_mbist_fault_C06,
    output logic             mem2_mbist_fault_C07,
    output logic             mem2_mbist_fault_C08,
    output logic             mem2_mbist_fault_C09,
    output logic             mem2_mbist_fault_C10,
    output logic             mem2_mbist_fault_C11,
    output logic             mem2_mbist_fault_C12,
    output logic             mem2_mbist_fault_C13,
    output logic             mem2_mbist_fault_C14,
    output logic             mem2_mbist_fault_C15,
    output logic             mem2_mbist_fault_C16,
    output logic       [7:0] mem2_mbist_fault_state_C01,
    output logic       [7:0] mem2_mbist_fault_state_C02,
    output logic       [7:0] mem2_mbist_fault_state_C03,
    output logic       [7:0] mem2_mbist_fault_state_C04,
    output logic       [7:0] mem2_mbist_fault_state_C05,
    output logic       [7:0] mem2_mbist_fault_state_C06,
    output logic       [7:0] mem2_mbist_fault_state_C07,
    output logic       [7:0] mem2_mbist_fault_state_C08,
    output logic       [7:0] mem2_mbist_fault_state_C09,
    output logic       [7:0] mem2_mbist_fault_state_C10,
    output logic       [7:0] mem2_mbist_fault_state_C11,
    output logic       [7:0] mem2_mbist_fault_state_C12,
    output logic       [7:0] mem2_mbist_fault_state_C13,
    output logic       [7:0] mem2_mbist_fault_state_C14,
    output logic       [7:0] mem2_mbist_fault_state_C15,
    output logic       [7:0] mem2_mbist_fault_state_C16,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C01,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C02,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C03,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C04,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C05,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C06,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C07,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C08,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C09,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C10,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C11,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C12,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C13,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C14,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C15,
    output logic [addrW-1:0] mem2_mbist_fault_addr_C16,
    output logic [dataW-1:0] mem2_mbist_fault_data_C01,
    output logic [dataW-1:0] mem2_mbist_fault_data_C02,
    output logic [dataW-1:0] mem2_mbist_fault_data_C03,
    output logic [dataW-1:0] mem2_mbist_fault_data_C04,
    output logic [dataW-1:0] mem2_mbist_fault_data_C05,
    output logic [dataW-1:0] mem2_mbist_fault_data_C06,
    output logic [dataW-1:0] mem2_mbist_fault_data_C07,
    output logic [dataW-1:0] mem2_mbist_fault_data_C08,
    output logic [dataW-1:0] mem2_mbist_fault_data_C09,
    output logic [dataW-1:0] mem2_mbist_fault_data_C10,
    output logic [dataW-1:0] mem2_mbist_fault_data_C11,
    output logic [dataW-1:0] mem2_mbist_fault_data_C12,
    output logic [dataW-1:0] mem2_mbist_fault_data_C13,
    output logic [dataW-1:0] mem2_mbist_fault_data_C14,
    output logic [dataW-1:0] mem2_mbist_fault_data_C15,
    output logic [dataW-1:0] mem2_mbist_fault_data_C16,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C01,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C02,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C03,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C04,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C05,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C06,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C07,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C08,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C09,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C10,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C11,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C12,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C13,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C14,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C15,
    output logic [dataW-1:0] mem2_mbist_fault_dout_C16,
    output logic             mem2_mbist_done_C01_C02,
    output logic             mem2_mbist_done_C03_C04,
    output logic             mem2_mbist_done_C05_C06,
    output logic             mem2_mbist_done_C07_C08,
    output logic             mem2_mbist_done_C09_C10,
    output logic             mem2_mbist_done_C11_C12,
    output logic             mem2_mbist_done_C13_C14,
    output logic             mem2_mbist_done_C15_C16
  );

    //MEM1 Instance
    memory_model #(
      .base_index(parallel_mems*mem_sections*0),
      .mem_len(fault_count),
      .parallel_mems(parallel_mems),
      .mem_sections(mem_sections),
      .fault_count(fault_count/2),
      .disturb_count(disturb_count),
      .couple_count(couple_count),
      .watch_depth(watch_depth),
      .addrW(addrW),
      .dataW(dataW)
    ) MEM1 (
      `ifndef SYNTHESIS
      .log_fd(log_fd),
      `endif
      .clk(clk),
      .nres(nres),
      //Memory Port
      .cs_n(mem1_cs_n),
      .addr(mem1_addr),
      // Write
      .we_n(mem1_we_n),
      .bwe_n(mem1_bwe_n),
      .din(mem1_din),
      // Read
      .re_n(mem1_re_n),
      .dout(mem1_dout),
      //MBIST Interface
      .mbist_mode(mem1_mbist_mode),
      .mbist_en({
        mem1_mbist_en_C01_C02,
        mem1_mbist_en_C03_C04,
        mem1_mbist_en_C05_C06,
        mem1_mbist_en_C07_C08,
        mem1_mbist_en_C09_C10,
        mem1_mbist_en_C11_C12,
        mem1_mbist_en_C13_C14,
        mem1_mbist_en_C15_C16
      }),
      .mbist_fault({
        mem1_mbist_fault_C01,
        mem1_mbist_fault_C02,
        mem1_mbist_fault_C03,
        mem1_mbist_fault_C04,
        mem1_mbist_fault_C05,
        mem1_mbist_fault_C06,
        mem1_mbist_fault_C07,
        mem1_mbist_fault_C08,
        mem1_mbist_fault_C09,
        mem1_mbist_fault_C10,
        mem1_mbist_fault_C11,
        mem1_mbist_fault_C12,
        mem1_mbist_fault_C13,
        mem1_mbist_fault_C14,
        mem1_mbist_fault_C15,
        mem1_mbist_fault_C16
      }),
      .mbist_fault_state({
        mem1_mbist_fault_state_C01,
        mem1_mbist_fault_state_C02,
        mem1_mbist_fault_state_C03,
        mem1_mbist_fault_state_C04,
        mem1_mbist_fault_state_C05,
        mem1_mbist_fault_state_C06,
        mem1_mbist_fault_state_C07,
        mem1_mbist_fault_state_C08,
        mem1_mbist_fault_state_C09,
        mem1_mbist_fault_state_C10,
        mem1_mbist_fault_state_C11,
        mem1_mbist_fault_state_C12,
        mem1_mbist_fault_state_C13,
        mem1_mbist_fault_state_C14,
        mem1_mbist_fault_state_C15,
        mem1_mbist_fault_state_C16
      }),
      .mbist_fault_addr({
        mem1_mbist_fault_addr_C01,
        mem1_mbist_fault_addr_C02,
        mem1_mbist_fault_addr_C03,
        mem1_mbist_fault_addr_C04,
        mem1_mbist_fault_addr_C05,
        mem1_mbist_fault_addr_C06,
        mem1_mbist_fault_addr_C07,
        mem1_mbist_fault_addr_C08,
        mem1_mbist_fault_addr_C09,
        mem1_mbist_fault_addr_C10,
        mem1_mbist_fault_addr_C11,
        mem1_mbist_fault_addr_C12,
        mem1_mbist_fault_addr_C13,
        mem1_mbist_fault_addr_C14,
        mem1_mbist_fault_addr_C15,
        mem1_mbist_fault_addr_C16
      }),
      .mbist_fault_data({
        mem1_mbist_fault_data_C01,
        mem1_mbist_fault_data_C02,
        mem1_mbist_fault_data_C03,
        mem1_mbist_fault_data_C04,
        mem1_mbist_fault_data_C05,
        mem1_mbist_fault_data_C06,
        mem1_mbist_fault_data_C07,
        mem1_mbist_fault_data_C08,
        mem1_mbist_fault_data_C09,
        mem1_mbist_fault_data_C10,
        mem1_mbist_fault_data_C11,
        mem1_mbist_fault_data_C12,
        mem1_mbist_fault_data_C13,
        mem1_mbist_fault_data_C14,
        mem1_mbist_fault_data_C15,
        mem1_mbist_fault_data_C16
      }),
      .mbist_fault_dout({
        mem1_mbist_fault_dout_C01,
        mem1_mbist_fault_dout_C02,
        mem1_mbist_fault_dout_C03,
        mem1_mbist_fault_dout_C04,
        mem1_mbist_fault_dout_C05,
        mem1_mbist_fault_dout_C06,
        mem1_mbist_fault_dout_C07,
        mem1_mbist_fault_dout_C08,
        mem1_mbist_fault_dout_C09,
        mem1_mbist_fault_dout_C10,
        mem1_mbist_fault_dout_C11,
        mem1_mbist_fault_dout_C12,
        mem1_mbist_fault_dout_C13,
        mem1_mbist_fault_dout_C14,
        mem1_mbist_fault_dout_C15,
        mem1_mbist_fault_dout_C16
      }),
      .mbist_done({
        mem1_mbist_done_C01_C02,
        mem1_mbist_done_C03_C04,
        mem1_mbist_done_C05_C06,
        mem1_mbist_done_C07_C08,
        mem1_mbist_done_C09_C10,
        mem1_mbist_done_C11_C12,
        mem1_mbist_done_C13_C14,
        mem1_mbist_done_C15_C16
      })
    );

    //MEM2 Instance
    memory_model #(
      .base_index(parallel_mems*mem_sections*1),
      .mem_len(fault_count),
      .parallel_mems(parallel_mems),
      .mem_sections(mem_sections),
      .fault_count(fault_count/2),
      .disturb_count(disturb_count),
      .couple_count(couple_count),
      .watch_depth(watch_depth),
      .addrW(addrW),
      .dataW(dataW)
    ) MEM2 (
      `ifndef SYNTHESIS
      .log_fd(log_fd),
      `endif
      .clk(clk),
      .nres(nres),
      //Memory Port
      .cs_n(mem2_cs_n),
      .addr(mem2_addr),
      // Write
      .we_n(mem2_we_n),
      .bwe_n(mem2_bwe_n),
      .din(mem2_din),
      // Read
      .re_n(mem2_re_n),
      .dout(mem2_dout),
      //MBIST Interface
      .mbist_mode(mem2_mbist_mode),
      .mbist_en({
        mem2_mbist_en_C01_C02,
        mem2_mbist_en_C03_C04,
        mem2_mbist_en_C05_C06,
        mem2_mbist_en_C07_C08,
        mem2_mbist_en_C09_C10,
        mem2_mbist_en_C11_C12,
        mem2_mbist_en_C13_C14,
        mem2_mbist_en_C15_C16
      }),
      .mbist_fault({
        mem2_mbist_fault_C01,
        mem2_mbist_fault_C02,
        mem2_mbist_fault_C03,
        mem2_mbist_fault_C04,
        mem2_mbist_fault_C05,
        mem2_mbist_fault_C06,
        mem2_mbist_fault_C07,
        mem2_mbist_fault_C08,
        mem2_mbist_fault_C09,
        mem2_mbist_fault_C10,
        mem2_mbist_fault_C11,
        mem2_mbist_fault_C12,
        mem2_mbist_fault_C13,
        mem2_mbist_fault_C14,
        mem2_mbist_fault_C15,
        mem2_mbist_fault_C16
      }),
      .mbist_fault_state({
        mem2_mbist_fault_state_C01,
        mem2_mbist_fault_state_C02,
        mem2_mbist_fault_state_C03,
        mem2_mbist_fault_state_C04,
        mem2_mbist_fault_state_C05,
        mem2_mbist_fault_state_C06,
        mem2_mbist_fault_state_C07,
        mem2_mbist_fault_state_C08,
        mem2_mbist_fault_state_C09,
        mem2_mbist_fault_state_C10,
        mem2_mbist_fault_state_C11,
        mem2_mbist_fault_state_C12,
        mem2_mbist_fault_state_C13,
        mem2_mbist_fault_state_C14,
        mem2_mbist_fault_state_C15,
        mem2_mbist_fault_state_C16
      }),
      .mbist_fault_addr({
        mem2_mbist_fault_addr_C01,
        mem2_mbist_fault_addr_C02,
        mem2_mbist_fault_addr_C03,
        mem2_mbist_fault_addr_C04,
        mem2_mbist_fault_addr_C05,
        mem2_mbist_fault_addr_C06,
        mem2_mbist_fault_addr_C07,
        mem2_mbist_fault_addr_C08,
        mem2_mbist_fault_addr_C09,
        mem2_mbist_fault_addr_C10,
        mem2_mbist_fault_addr_C11,
        mem2_mbist_fault_addr_C12,
        mem2_mbist_fault_addr_C13,
        mem2_mbist_fault_addr_C14,
        mem2_mbist_fault_addr_C15,
        mem2_mbist_fault_addr_C16
      }),
      .mbist_fault_data({
        mem2_mbist_fault_data_C01,
        mem2_mbist_fault_data_C02,
        mem2_mbist_fault_data_C03,
        mem2_mbist_fault_data_C04,
        mem2_mbist_fault_data_C05,
        mem2_mbist_fault_data_C06,
        mem2_mbist_fault_data_C07,
        mem2_mbist_fault_data_C08,
        mem2_mbist_fault_data_C09,
        mem2_mbist_fault_data_C10,
        mem2_mbist_fault_data_C11,
        mem2_mbist_fault_data_C12,
        mem2_mbist_fault_data_C13,
        mem2_mbist_fault_data_C14,
        mem2_mbist_fault_data_C15,
        mem2_mbist_fault_data_C16
      }),
      .mbist_fault_dout({
        mem2_mbist_fault_dout_C01,
        mem2_mbist_fault_dout_C02,
        mem2_mbist_fault_dout_C03,
        mem2_mbist_fault_dout_C04,
        mem2_mbist_fault_dout_C05,
        mem2_mbist_fault_dout_C06,
        mem2_mbist_fault_dout_C07,
        mem2_mbist_fault_dout_C08,
        mem2_mbist_fault_dout_C09,
        mem2_mbist_fault_dout_C10,
        mem2_mbist_fault_dout_C11,
        mem2_mbist_fault_dout_C12,
        mem2_mbist_fault_dout_C13,
        mem2_mbist_fault_dout_C14,
        mem2_mbist_fault_dout_C15,
        mem2_mbist_fault_dout_C16
      }),
      .mbist_done({
        mem2_mbist_done_C01_C02,
        mem2_mbist_done_C03_C04,
        mem2_mbist_done_C05_C06,
        mem2_mbist_done_C07_C08,
        mem2_mbist_done_C09_C10,
        mem2_mbist_done_C11_C12,
        mem2_mbist_done_C13_C14,
        mem2_mbist_done_C15_C16
      })
    );
    `endif

endmodule